id = "019f04aa-ecc6-7450-89db-78a925cc1e1c"
ref = "gitrack-vee"
title = "Default priority from config"
body = "We should not enforce a hardcoded default priority in create. Every creator should specify priority explicitly during create, or set a default priority in the config during init, since different workflows have different models. If they want to change it, they can just update the config file manually. I don't want to sprawls the CI size too much"
status = "open"
type = "task"
priority = 3
created_at = "2026-06-26T16:02:18.438979Z"
updated_at = "2026-06-26T16:02:18.438979Z"
